dd Python 3.12 Support / Remove Python 3.8 Support
dbt-labs/metricflow pull request #1066
Opened 2024-03-07 17:57 UTC by plypaul

Resolves #1065 

### Description

This PR updates the code and Github workflows to support Python 3.12 and to remove support for Python 3.8.

2024-03-11 18:44 UTC, tlento requested changes
Per discussion, we probably need to do a bunch of annoying stuff to keep 3.8 through 3.12 here. Sigh.

2024-03-11 18:44 UTC, tlento commented on pyproject.toml
> +requires-python = ">=3.9,<=3.12"
Python 3.8 is supported through October, so we need to to support 3.8 through the dbt-core release following official EOL.

2024-03-11 18:44 UTC, tlento commented on pyproject.toml
> +  "pandas>=2.1, <2.2",
This is super restrictive, I don't think we can block 1.x installs.

Medium term I'd like to just remove pandas as a production dependency altogether, we don't need it for anything.

2024-03-11 18:44 UTC, tlento commented on pyproject.toml
> +  "python-dateutil~=2.9.0",
Please don't use ~= syntax, it breaks PIP resolvers in certain edge cases.

2024-03-11 18:44 UTC, tlento commented on pyproject.toml
> +  "pytest~=8.0",
No ~= please.

2024-05-30 00:18 UTC, plypaul commented
Closing this out as this was significantly revised, and related changes will be in a another PR.

2024-05-30 00:18 UTC, closed without merging