Enable different granularities for metrics with time offset
dbt-labs/metricflow pull request #426
Opened 2023-02-03 19:33 UTC by courtneyholcomb

With the current placement of the `JoinToTimeSpineNode` in the dataflow plan, time granularity aggregation happens before joining to time spine, which means queries with any granularity besides `DAY` don't return expected results. Here, we move the time spine join to happen before granularity aggregation.
For cumulative metrics, we also move the `FilterElementsNode` to after the `JoinOverTimeRange` node to ensure we keep all columns needed when joining to time spine.

2023-02-06 21:44 UTC, courtneyholcomb commented on metricflow/test/fixtures/model_yamls/simple_model/metrics.yaml
> -  name: "every_two_days_bookers" # because the bookings test data only spans 3 days
No longer true

2023-02-06 21:45 UTC, courtneyholcomb commented on metricflow/plan_conversion/dataflow_to_sql.py
> -            return SqlDataSet(
Removed some redundant code here

2023-05-19 22:16 UTC, plypaul requested changes
As per discussion, there are some uncertainties on how the feature should work (from a product perspective), and we haven't prioritized a resolution. Since I'm using github to manage my review queue, marking this is `Request Changes` so that it's not on my list.

2023-08-16 01:09 UTC, courtneyholcomb commented
PR outdated; new one here https://github.com/dbt-labs/metricflow/pull/726

2023-08-16 01:09 UTC, closed without merging