Remove GitPython dependency from MetricFlow
dbt-labs/metricflow pull request #545
Opened 2023-05-22 23:38 UTC by tlento

resolves #

### Description

<!--- 
  Before requesting review, please make sure you have:
  1. read [the contributing guide](https://github.com/dbt-labs/metricflow/blob/main/CONTRIBUTING.md),
  2. signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
  3. run `changie new` to [create a changelog entry](https://github.com/dbt-labs/metricflow/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2023-05-22 23:38 UTC, tlento commented
Current dependencies on/for this PR:
* main
  * **PR #545** <a href="https://app.graphite.dev/github/pr/dbt-labs/metricflow/545" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dbt-labs/metricflow/545?utm_source=stack-comment).

2023-05-25 18:53 UTC, plypaul commented
Strange that there are changes by `ruff`. How did you run `pre-commit`?

2023-05-25 20:29 UTC, tlento commented
Well that's annoying, Ruff in CI appears to be just reverting my local Ruff-produced changes. Sigh.

2023-05-25 22:18 UTC, plypaul requested changes
@tlento - Can you check if have an empty directory `dbt-semantic-interfaces`? If that's present, ruff will think that's a local package and change the way it does imports.

2023-05-25 23:56 UTC, tlento commented
@plypaul it wasn't empty! I think it must've come back when I changed branches while the removal PR was out for review.

2023-05-26 00:01 UTC, plypaul approved these changes

2023-05-26 00:14 UTC, merged