Get dimension values via SQL
dbt-labs/metricflow pull request #566
Opened 2023-06-02 18:32 UTC by WilliamDee

resolves #

### Description

<!--- 
  Before requesting review, please make sure you have:
  1. read [the contributing guide](https://github.com/dbt-labs/metricflow/blob/main/CONTRIBUTING.md),
  2. signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
  3. run `changie new` to [create a changelog entry](https://github.com/dbt-labs/metricflow/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2023-06-05 19:34 UTC, WilliamDee commented on metricflow/engine/metricflow_engine.py
> +    def explain_get_dimension_values(  # noqa: D
there has to be a better name here, but I can't figure it out. Any advice is appreciated or we can leave it as it 🙈

2023-06-06 20:05 UTC, plypaul requested changes
Looks good overall, but can you add a check so that entities can't be queried as dimension values. Since I'm using github to manage the review queue, sending back with `request changes` even though this is minor.

2023-06-06 20:05 UTC, plypaul commented on metricflow/dataflow/builder/dataflow_plan_builder.py
> +        filter_by_specs: Optional[InstanceSpecSet] = None,
Maybe `output_selection_specs`?

2023-06-08 17:45 UTC, plypaul approved these changes

2023-06-08 17:46 UTC, merged